apiVersion: v1
kind: Service
metadata:
  name: mc-vanilla
  labels:
    app: mc-vanilla
spec:
  ports:
  - port: 25565
    targetPort: 25565
    name: minecraft
  - port: 25575
    targetPort: 25575
    name: rcon
  selector:
    app: mc-vanilla
  type: LoadBalancer
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mc-vanilla
spec:
  selector:
    matchLabels:
      app: mc-vanilla
  serviceName: "mc-vanilla"
  replicas: 1
  template:
    metadata:
      labels:
        app: mc-vanilla
    spec:
      # https://kubernetes.io/docs/tasks/run-application/force-delete-stateful-set-pod/ ?
      # terminationGracePeriodSeconds: 13
      containers:
      # Using a fixed release tag always prevents unexpected surprises!
      - image: itzg/minecraft-server:2021.22.0-java16-openj9
        name: mc-vanilla
        resources:
          requests:
            # https://cloud.google.com/kubernetes-engine/docs/concepts/autopilot-overview#allowable_resource_ranges
            # The 512 should avoid "Warning: Autopilot increased resource requests (...) to meet requirements."
            memory: "512Mi"
            cpu: "2"
          limits:
            memory: "2048Mi"
            cpu: "4"
        env:
        # https://github.com/OASIS-learn-study/kubernetes.oasis.learn.study#memory-management
        - name: JVM_XX_OPTS
          # NB that e.g. USE_AIKAR_FLAGS doesn't really make sense anymore with OpenJ9, let's fail fast to avoid confusion
          value: "-XX:-IgnoreUnrecognizedXXColonOptions"
        - name: INIT_MEMORY
          # this lets the JVM return unused heap memory to the OS!
          value: "500M"
        - name: MAX_MEMORY
          # should probably be something a bit lower than container memory limit, but exactly is TBD
          value: "1800M"
        - name: USE_LARGE_PAGES
          value: "true"
        - name: TUNE_VIRTUALIZED
          # https://www.eclipse.org/openj9/docs/xtunevirtualized/
          value: "true"
        - name: TUNE_NURSERY_SIZES
          value: "true"
        # Now other stuff not related to memory managment
        - name: RCON_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mc-vanilla
              key: rcon
        - name: ENABLE_RCON
          value: "true"
        - name: VERSION
          # https://github.com/itzg/docker-minecraft-server#versions
          value: "1.17.1"
        - name: MODE
          value: "1"
        - name: MOTD
          value: "Minecraft Demo on Kubernetes"
        - name: EULA
          value: "true"
        ports:
        - containerPort: 25565
          name: minecraft
        - containerPort: 25575
          name: rcon
#        readinessProbe:
#          exec:
#            command:
#            - mc-monitor
#            - status
#          initialDelaySeconds: 300
#          periodSeconds: 300
#        livenessProbe:
#          exec:
#            command:
#            - mc-monitor
#            - status
#          initialDelaySeconds: 300
#          periodSeconds: 300
        volumeMounts:
        - name: mc-data
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: mc-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      # storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi
