settings:
  key:
  - 15
  - 164
  - 79
  - 186
  - 218
  - 7
  - 131
  - 36
  - 147
  - 126
  - 167
  - 206
  - 235
  - 203
  - 69
  - 158
  - 253
  - 63
  - 110
  - 202
  - 106
  - 157
  - 26
  - 82
  - 15
  - 160
  - 168
  - 85
  - 255
  - 65
  - 250
  - 95
  - 122
  - 189
  - 20
  - 86
  - 140
  - 65
  - 234
  - 167
  - 41
  - 128
  - 75
  - 154
  - 36
  - 211
  - 134
  - 79
  - 33
  - 236
  - 66
  - 150
  - 93
  - 178
  - 221
  - 232
  - 207
  - 14
  - 84
  - 140
  - 246
  - 181
  - 139
  - 216
  signup: false
  createuserdir: false
  defaults:
    scope: .
    locale: en
    viewmode: list
    singleclick: false
    sorting:
      by: name
      asc: false
    perm:
      admin: true
      execute: true
      create: true
      rename: true
      modify: true
      delete: true
      share: true
      download: true
    commands: []
    hidedotfiles: false
    dateformat: false
  authmethod: noauth
  branding:
    name: ""
    disableexternal: false
    files: ""
    theme: ""
    color: ""
  commands:
    after_copy: []
    after_delete: []
    after_rename: []
    after_save: []
    after_upload: []
    before_copy: []
    before_delete: []
    before_rename: []
    before_save: []
    before_upload: []
  shell: []
  rules: []
server:
  root: /srv
  baseurl: ""
  socket: ""
  tlskey: ""
  tlscert: ""
  port: "80"
  address: ""
  log: stdout
  enablethumbnails: false
  resizepreview: false
  enableexec: false
  typedetectionbyheader: false
auther: {}
